---
title: "Milestone4"
author: "Nick Maxwell"
date: "10/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstanarm)

```

```{r import data}
justiceCentered <- 
  read_csv("SCDB_2020_01_justiceCentered_LegalProvision.csv",
           col_types = cols())

# Here, I'm importing the data from the University of Washington Law School as
# described on my "about" page. The col_types that the code defaults to work,
# so there wasn't any need to change.

justiceIdeology <- read_csv("justices.csv",
                            col_types = cols())

# This data is the University of Michigan data as described in the "about" page
# in my shiny app. Again, the default col_types work, so there was no need to
# change it.

```

```{r clean data}
substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

# This is a simple function that allows me to grab the last four characters of a
# given input. For this project, I'll be using it on the dateDecision column of
# the justiceCentered tibble to grab the year of the decision.

justiceIdeologyyear <- justiceIdeology %>% 
  mutate(year = term) %>% 
  select(-term)

 # Making year rather than term appear for simplicity and for potential binding
 # value later.

roberts <- justiceCentered %>% 
  mutate(year = as.numeric(substrRight(dateDecision, 4))) %>% 
  filter(chief == "Roberts")

 # For this project, I'm only looking at the Roberts court, so we'll filter to
 # that effect and calculate the year in this dataset using the function I
 # defined above.

roberts_small <- roberts %>% 
  select(year, justiceName, justice, direction, issue, issueArea)

 # I'll only need these columns for this data, so I'm going to select them here
 # so I can speed along processing time since we're working with a big dataset.

joined_data <- left_join(roberts_small, justiceIdeologyyear, 
                  by = c("year" = "year", 
                  "justice" = "justice",
                  "justiceName" = "justiceName")) %>% 
                   mutate(justiceName = recode(justiceName, 
                                      "SDOConnor" = "O'Connor",
                                      "JPStevens" = "Stevens",
                                      "AScalia" = "Scalia",
                                      "AMKennedy" = "Kennedy",
                                      "DHSouter" = "Souter",
                                      "CThomas" = "Thomas",
                                      "RBGinsburg" = "Ginsburg",
                                      "SGBreyer" = "Breyer",
                                      "JGRoberts" = "Roberts",
                                      "SAAlito" = "Alito",
                                      "SSotomayor" = "Sotomayor",
                                      "EKagan" = "Kagan",
                                      "NMGorsuch" = "Gorsuch",
                                      "BMKavanaugh" = "Kavanaugh")) %>% 
  
  # Here, I'm manually recoding the justice names as they appear in the data
  # originally to be more display-friendly in my shinyapp.
  
                 mutate(issueArea = recode(issueArea,
                                           "1" = "Criminal Procedure",
                                           "2" = "Civil Rights",
                                           "3" = "First Amendment",
                                           "4" = "Due Process",
                                           "5" = "Privacy",
                                           "6" = "Attorneys",
                                           "7" = "Unions",
                                           "8" = "Economic Activity",
                                           "9" = "Judicial Power",
                                           "10" = "Federalism",
                                           "11" = "Interstate Relations",
                                           "12" = "Federal Taxation",
                                           "13" = "Miscellaneous",
                                           "14" = "Private Action")) %>% 
  
  # Using the codebook provided in the University of Michigan dataset, I'm
  # simply recoding the issue areas to what they represent.
  
                 mutate(direction = as.factor(recode(direction,
                                           "1" = "Conservative",
                                           "2" = "Liberal"))) %>% 
                 mutate(conservative = as.factor(ifelse(direction == 
                                                "Conservative", 1, 0))) %>% 
  
  # With these transformations, I'm creating a "conservative" column that will
  # allow me to predict the conservative direction more easily, as that's the
  # unit of analysis that will be most useful for this project. I thought for a
  # bit of how to do this, but simply coding the direction based on the
  # Washington University dataset to the ideology of the direction and then
  # creating a new column for conservatism made sense in my head and allowed me
  # to be sure there wouldn't be an error in such an important column.
  
                 mutate(justiceName = as.factor(justiceName),
                        issueArea = as.factor(issueArea)) %>%
  
  # Because of their limited number and the analysis that we will be doing
  # later, coding both the issues and justices as factors now that they're in
  # their final forms makes sense.
  
                 mutate(year = as.integer(year)) %>%
                 drop_na()

# This is a long join. The idea here is to merge the "roberts_small" dataset,
# which contains decisions for each case during the Roberts term, with the
# "justiceIdeologyyear" dataset, which contains Martin-Quinn ideology scores for
# each justice for each year. This will allow us to run a regression to predict
# vote outcome probabilities for different issues depending on these ideology
# scores. I needed to do a bit of cleaning here to get the justice names in a
# more friendly format, code the issue areas so that they are easily readable,
# and then recode the "conservative" variable, as well as factor transform a few
# other variables. At the end, this was saved as an RDS file called
# "roberts.rds"

```

```{r ideological history plot}
roberts_issue_area_votes <- joined_data %>% 
  mutate(conservative = as.integer(conservative) - 1) %>% 
  select(justiceName, issueArea, conservative) %>% 
  drop_na() %>% 
  group_by(issueArea, justiceName) %>% 
  summarize(percentage = mean(conservative), .groups = "drop") 

# This quick dataset allows us to visualize the proportion of conservative votes
# for each justice for each issue area. I've saved this as a .rds file so I can
# quickly use it in my Shiny App. Specifically, it is titled
# "robertsissues.rds"

```

```{r prediction model}
new_tibble <- tibble(post_mn = rep(seq(-4, 4, .1), 13),
                   issueArea = rep(c("Criminal Procedure", "Civil Rights",
                    "First Amendment", "Due Process", "Privacy", "Attorneys",
                    "Unions", "Economic Activity", "Judicial Power", 
                    "Federalism", "Federal Taxation", "Miscellaneous",
                    "Private Action"), each = 81))

# Here, I'm creating a new tibble that will serve as the newdata for my
# posterior predict. After experimenting a bit, it made sense to have inputted
# ideology scores at increments of .1, allowing for 81  data points for each
# issue. This allowed for enough precision to see meaningful differences in the
# trends while allowing for run time constraints and making sure we don't get
# tripped up with irrelevant noise. As a note, I drop the "interstate relations"
# issue here, as there were not enough cases during the Roberts Court to make
# any meaningful conclusions. Thus, we're down to 13 issue areas. We then have
# each value from -4 to 4 by 0.1 (81 numbers) and each issue (13) issue areas
# defined as above.

prediction_model <- stan_glm(conservative ~ issueArea*post_mn,
                             data = joined_data,
                             refresh = 0,
                             binomial(link = "logit"))

# As explained in the shinyapp, this model allows us to predict a conservative
# vote by issue area and a theoretical ideology score (post_mn). Including their
# interaction is important here as well, as, conceptually, we would think that
# ideology would impact different issues differently.

all_issue_ideology <- posterior_predict(prediction_model, 
                                        newdata = new_tibble) %>%
    as_tibble() %>%
    mutate_all(as.numeric) %>% 
  
  # Standard method of generating a posterior distribution using our model and
  # the new_tibble we created above.
  
    summarize_all(mean) %>% 
  
  # Here, we use the summarize command with mean to get the probability of
  # voting conservative on that issue for that given ideology score.
  
    pivot_longer(cols = everything(),
               names_to = "ideology_score",
               values_to = "outcome") %>% 
  
  # Standard pivot_longer here to get our data into a format that we can more
  # easily work with it.
  
    bind_cols(new_tibble) %>% 
  
  # Because we haven't altered the order of anything, we're able to use the
  # bind_cols command with our new_tibble that we created to allow our outcomes
  # to perfectly align with the correct issue area and baseline ideology score.
  # Almost like magic! With the data in this form, we will be able to graph the
  # results easily using a simple line plot.
  
    select(-ideology_score)

# This is the full code for the logistic regression that will allow us to
# predict a conservative vote for a given issue area. To combine precision with
# feasibility as far as run time, I used a step of 0.1 to cover the ideology
# scores of -4 to 4. I then had each value repeated for each issue area in the
# dataset. After running a simple logistic regression, I was able to use
# posterior predict (and after some data wrangling/transformation) to create a
# tibble that has the probability of a conservative vote for each issue area for
# each baseline Martin-Quinn ideology score. I then saved this tibble as a .rds
# object so that I can easily graph the relevant data in a ggplot in the Shiny
# App. Originally, I ran the model in the Shiny App itself, but this led to long
# lag times and long upload times. Running all of the calculations and saving
# the results in a .rds file is far more efficient. The RDS file is called
# posterior_all_issue_ideology.rds"

```


