---
title: "Milestone 2"
author: "Nick Maxwell"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Link to repo: https://github.com/ndmaxwell/finalproject.git




First Project: Amy Zhou's "Caselaw Through the Years" 
https://amy-zhou16.shinyapps.io/caselaw_analysis/

  Because I'm interested in doing a project on the Supreme Court, this project seemed like a natural one to review. As far as pros for this project, I would say that it provides a thorough overview of the court system across the country in a unique and comprehensive way. Rather than simply looking at the Supreme Court, Amy includes data from across state courts as well the Supreme Court to account for regional differences. Clearly, this required a lot more data gathering/cleaning than it might otherwise have by just limited the analysis to the federal level. 

  As far as cons of this project, I would say that it doesn't offer as much insight as the "why" question for the topics presented. In the aggregation of case counts and word usage, we aren't given much insight as to the context of why the case load may have shifted over time or what context the words were used in. Including how many of the cases originated in the different courts and then were either appealed or settled at what level could have been an interesting point of comparison. 

  Amy attempts to do this in her analyis of cases won by gender, but these thoughts are not based on the data as much as they are reasons offered as potential explanations. Although they seem plausible to me, I would have appreciated an additional layer of analysis that would have explored whether, like she said, women who are petitioners truly have a "better" case on average or if another explanation exists. Perhaps women are disproportionately the petitioners for certain "buckets" of cases and they have tend to come out one way versus another. 




Second Project: Elizabeth Guo's "Demographics and Votes in the U.S. Supreme Court"
https://elizabeth-guo.shinyapps.io/supreme_court/

  One pro of the way that Elizabeth structured her project is that all of the pieces work cohesively toward specific questions. Building on the data she put together regarding religion and then later party affiliation/nominating president, the project allows us an interesting look into the question of whether Justices are simply "politicians in robes." In particular, the historical depth of this project is compelling, with data going back as far as the 18th century for some of the pieces of analysis. The visualizations at the end are well done, though there are certain questions that remain unanswered from the data she gathered and analyzed. 

  In particular, she concludes that, often, Justices do not vote along party lines. However, from the way the data is presented in its current form, it's unclear whether that is disproportionately from certain Justices being nominated by a party of one president and then consistently voting for the other side (the prime case being Justice Souter), or whether many Justices frequently vote against their ideological/political positions depending on the circumstances of the case. My guess would be the former, but it is hard to tell from the data that is included here.

  As a final note, it also seems that this project, while laudable for its extensive data gathering, could have potentially been streamlined/simplified (at least in the final presentation/this detail could have been clarified) with an analysis of the correlation between some of the key variables. One would imagine a very high correlation between a Justice's party affiliation and the party affiliation of the nominating president (likely close to 1.0). It also would have been interesting to see the correlation between religious affiliation and nominating party. A correlation matrix could have been a welcome addition to the "Can We Predict Justice Votes? 1948-2018" tab of the project.
